### PR TITLE
Rename virtual server to virtual service, add virtual service names as labels

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Fixes https://github.com/giantswarm/prometheus-kemp-exporter/issues/9 and fixes https://github.com/giantswarm/prometheus-kemp-exporter/issues/10

- [x] Update kemp-client dependency to released version

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
@xh3b4sd RFR

**Comment by hectorj2f** [comment]
@JosephSalisbury Why a branch name ? I don't understand it.

**Comment by xh3b4sd** [comment]
LGTM

**Comment by JosephSalisbury** [comment]
@hectorj2f this is the stuff i wanted for version `0.2.0`, so I named the branch that :D

**Pull request merged**
